# Generated by Django 3.1.2 on 2020-10-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.TextField()),
                ('amount', models.PositiveIntegerField(default=0)),
                ('parent_id', models.PositiveIntegerField()),
            ],
        ),
    ]
